### ISSUE TITLE
Support python3.10: "unexpected keyword argument 'loop'"

### ISSUE THREAD

**Issue by vincentdephily** [wwww-wwww/phxsocket#5]
I'm getting the following traceback when trying to open a channel on a connected socket (following the example from the readme):

```
ERROR:root:phxsocket: Traceback (most recent call last):
  File "/home/work/.local/lib/python3.11/site-packages/phxsocket/client.py", line 109, in run
    loop.run_until_complete(
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/work/.local/lib/python3.11/site-packages/phxsocket/client.py", line 97, in _run
    await asyncio.wait({listen, shutdown, broadcast},
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: wait() got an unexpected keyword argument 'loop'
```

According to [the python asincio docs](https://docs.python.org/3/library/asyncio-task.html#waiting-primitives) the `loop` argument was removed in python 3.10.

**Comment by wwww-wwww** [comment]
Updated. Can you try now?

**Comment by vincentdephily** [comment]
Thanks for the quick response !

The commit seems to be getting me through the first hurdle, though I'm now facing the fact that this server only exposes a Phoenix.Socket, no Phoenix.Channel (it's set up for absinthe subscriptions). So I can't yet 100% say that your fix worked for me, as I now need to figure out how to use phxsocket without channels.

**Comment by PenguinBoi12** [comment]
It does seem to fix the issue. I had the same issue when I was on 0.1.2 and after updating to 0.1.3 the problem disappeared.
